name: igasset-gen Integration Tests

on: [push]

jobs:
  build-and-test:
    runs-on: docker
    container: git.indigocode.dev/sessamekesh/emsdk-clang-box:0.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore dependency build cache
        uses: actions/cache@v3
        with:
          path: build/_deps
          key: deps-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', 'extern/CMakeLists.txt') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Configure
        run: >
          cmake -B build -G Ninja
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_CXX_SCAN_FOR_MODULES=OFF
          -DIGASYNC_BUILD_TESTS=OFF
          -DIGASYNC_BUILD_EXAMPLES=OFF

      - name: Build
        run: >
          cmake --build build
          --target igasset-gen
          --target enumerate-igasset
          --target igpack-bundle
          --target enumerate-igpack

      - name: Run igasset-gen Integration Tests
        env:
          IGASSET_GEN_BIN: build/tools/igasset-gen/igasset-gen
          ENUMERATE_IGASSET_BIN: build/tools/enumerate-igasset/enumerate-igasset
        run: pytest tools/igasset-gen/e2e/ -v

      - name: Run igpack-bundle Integration Tests
        env:
          IGASSET_GEN_BIN: build/tools/igasset-gen/igasset-gen
          IGPACK_BUNDLE_BIN: build/tools/igpack-bundle/igpack-bundle
          ENUMERATE_IGPACK_BIN: build/tools/enumerate-igpack/enumerate-igpack
        run: pytest tools/igpack-bundle/e2e/ -v
